const Lists = [
  [
    "Popular",
    "Arts & culture",
    "Outdoors",
    "Mountains",
    "Beach",
    "Unique Stays",
    "Categories",
    "Things to do",
  ],
  [
    { title: "Canmore", subTitle: "Flat rentals" },
    { title: "Tucson", subTitle: "Flat rentals" },
    { title: "Anaheim", subTitle: "Holiday rentals" },
    { title: "Dubai", subTitle: "Flat rentals" },
    { title: "Benalmádena", subTitle: "Beach house rentals" },
    { title: "Jasper", subTitle: "Holiday rentals" },
    { title: "Monterey", subTitle: "Cottage rentals" },
    { title: "Dubai", subTitle: "Flat rentals" },
    { title: "South West England", subTitle: "Cabin rentals" },
    { title: "Orlando", subTitle: "Cottage rentals" },
    { title: "Mykonos", subTitle: "Beachfront rentals" },
    { title: "St. Joseph", subTitle: "Cabin rentals" },
    { title: "Evans Head", subTitle: "Holiday rentals" },
    { title: "Lincoln City", subTitle: "Holiday rentals" },
    { title: "Scottish Highlands", subTitle: "Holiday rentals" },
    { title: "Birmingham", subTitle: "Cottage rentals" },
    { title: "Whitby", subTitle: "Flat rentals" },
    { title: "St Petersburg", subTitle: "Beach apartment rentals" },
    { title: "Santorini", subTitle: "House rentals" },
    { title: "Larsmont", subTitle: "Holiday rentals" },
    { title: "Sawtell", subTitle: "Cottage rentals" },
    { title: "Paphos", subTitle: "Holiday rentals" },
    { title: "St Andrews", subTitle: "Beachfront rentals" },
    { title: "Brighton", subTitle: "Cottage rentals" },
    { title: "Fort Myers", subTitle: "Beach house rentals" },
    { title: "St. Augustine", subTitle: "Flat rentals" },
    { title: "Oʻahu", subTitle: "Bungalow rentals" },
    { title: "Las Vegas", subTitle: "Holiday rentals" },
    { title: "Young", subTitle: "Holiday rentals" },
    { title: "Maleny", subTitle: "Holiday rentals" },
    { title: "McLaren Vale", subTitle: "House rentals" },
    { title: "Bude", subTitle: "Holiday rentals" },
    { title: "Jacksonville", subTitle: "House rentals" },
    { title: "The Villages", subTitle: "Pet-friendly rentals" },
    { title: "Capri", subTitle: "Flat rentals" },
    { title: "Madrid", subTitle: "Holiday rentals" },
    { title: "Ocracoke", subTitle: "House rentals" },
    { title: "Stanthorpe", subTitle: "House rentals" },
    { title: "Wallaroo", subTitle: "Beachfront rentals" },
    { title: "Kissimmee", subTitle: "Villa rentals" },
    { title: "Dahlonega", subTitle: "Cabin rentals" },
    { title: "Bar Harbor", subTitle: "Cabin rentals" },
    { title: "Santa Fe", subTitle: "Holiday rentals" },
    { title: "Florence", subTitle: "Apartment rentals" },
    { title: "Newport", subTitle: "Apartment rentals" },
    { title: "Charleston", subTitle: "House rentals" },
    { title: "Padstow", subTitle: "Cabin rentals" },
    { title: "Longboat Key", subTitle: "Pet-friendly rentals" },
    { title: "Crete", subTitle: "House rentals" },
    { title: "Mackinac Island", subTitle: "Holiday rentals" },
    { title: "Bermagui", subTitle: "Pet-friendly rentals" },
    { title: "Lakeside", subTitle: "Lakehouse rentals" },
    { title: "Glasgow", subTitle: "House rentals" },
    { title: "Hvar", subTitle: "Holiday rentals" },
    { title: "Scottish Highlands", subTitle: "Holiday rentals" },
    { title: "Saint John", subTitle: "Holiday rentals" },
    { title: "Waco", subTitle: "Cabin rentals" },
    { title: "Southwold", subTitle: "Holiday rentals" },
    { title: "Castlemaine", subTitle: "Holiday rentals" },
    { title: "Hay-on-Wye", subTitle: "Cottage rentals" },
    { title: "St Andrews", subTitle: "Beachfront rentals" },
    { title: "Chattanooga", subTitle: "Holiday rentals" },
    { title: "Forest of Dean District", subTitle: "Holiday rentals" },
    { title: "Staithes", subTitle: "Cottage rentals" },
    { title: "Healesville", subTitle: "Cottage rentals" },
    { title: "Llandudno", subTitle: "Flat rentals" },
    { title: "McLaren Vale", subTitle: "House rentals" },
    { title: "Concan", subTitle: "Cabin rentals" },
    { title: "Jersey", subTitle: "Flat rentals" },
    { title: "Wells-next-the-Sea", subTitle: "Holiday rentals" },
    { title: "Marysville", subTitle: "Cottage rentals" },
    { title: "Tenby", subTitle: "House rentals" },
    { title: "Wallaroo", subTitle: "Beachfront rentals" },
    { title: "Fredericksburg", subTitle: "Holiday rentals" },
    { title: "Lyme Regis", subTitle: "Chalet rentals" },
    { title: "St. George", subTitle: "House rentals" },
    { title: "Sorrento", subTitle: "House rentals" },
    { title: "Charleston", subTitle: "House rentals" },
    { title: "New Braunfels", subTitle: "Flat rentals" },
    { title: "Manchester", subTitle: "Holiday rentals" },
    { title: "Benidorm", subTitle: "Holiday rentals" },
    { title: "Chincoteague", subTitle: "Cottage rentals" },
    { title: "Hvar", subTitle: "Holiday rentals" },
    { title: "Rockport", subTitle: "Apartment rentals" },
    { title: "Seaview", subTitle: "Holiday rentals" },
    { title: "Barwon Heads", subTitle: "Pet-friendly rentals" },
    { title: "Williamsburg", subTitle: "Holiday rentals" },
    { title: "Scottish Highlands", subTitle: "Holiday rentals" },
    { title: "Saint John", subTitle: "Holiday rentals" },
    { title: "Waco", subTitle: "Cabin rentals" },
    { title: "Southwold", subTitle: "Holiday rentals" },
    { title: "Castlemaine", subTitle: "Holiday rentals" },
    { title: "Hay-on-Wye", subTitle: "Cottage rentals" },
    { title: "St Andrews", subTitle: "Beachfront rentals" },
    { title: "Chattanooga", subTitle: "Holiday rentals" },
    { title: "Forest of Dean District", subTitle: "Holiday rentals" },
    { title: "Staithes", subTitle: "Cottage rentals" },
    { title: "Healesville", subTitle: "Cottage rentals" },
    { title: "Llandudno", subTitle: "Flat rentals" },
    { title: "McLaren Vale", subTitle: "House rentals" },
    { title: "Concan", subTitle: "Cabin rentals" },
    { title: "Jersey", subTitle: "Flat rentals" },
  ],
  [
    { title: "Phoenix", subTitle: "House rentals" },
    { title: "Prague", subTitle: "Holiday rentals" },
    { title: "York", subTitle: "Cottage rentals" },
    { title: "Rome", subTitle: "Holiday rentals" },
    { title: "Duluth", subTitle: "Pet-friendly rentals" },
    { title: "Valencia", subTitle: "Cottage rentals" },
    { title: "Edinburgh", subTitle: "Flat rentals" },
    { title: "Seattle", subTitle: "Holiday rentals" },
    { title: "Hot Springs", subTitle: "Villa rentals" },
    { title: "Washington", subTitle: "House rentals" },
    { title: "Paris", subTitle: "Holiday rentals" },
    { title: "Lisbon", subTitle: "Rentals with pools" },
    { title: "Amsterdam", subTitle: "Holiday rentals" },
    { title: "Split", subTitle: "House rentals" },
    { title: "Liverpool", subTitle: "Flat rentals" },
    { title: "Los Angeles", subTitle: "Flat rentals" },
    { title: "Keswick", subTitle: "Flat rentals" },
    { title: "Rhodes", subTitle: "Rentals with pools" },
    { title: "Grand Isle", subTitle: "Pet-friendly rentals" },
    { title: "New York", subTitle: "Holiday rentals" },
    { title: "Nashville", subTitle: "Rentals with pools" },
    { title: "St Ives", subTitle: "House rentals" },
    { title: "San Diego", subTitle: "Rentals with pools" },
    { title: "London", subTitle: "Flat rentals" },
    { title: "New Orleans", subTitle: "Beach house rentals" },
    { title: "Nice", subTitle: "Cottage rentals" },
    { title: "Austin", subTitle: "Flat rentals" },
    { title: "Lake Powell", subTitle: "Holiday rentals" },
    { title: "San Francisco", subTitle: "Holiday rentals" },
    { title: "Scarborough", subTitle: "Holiday rentals" },
    { title: "Dublin", subTitle: "Holiday rentals" },
    { title: "Martha's Vineyard", subTitle: "Holiday rentals" },
    { title: "Inverness", subTitle: "Chalet rentals" },
    { title: "Houston", subTitle: "Holiday rentals" },
    { title: "Lake Anna", subTitle: "House rentals" },
    { title: "Barcelona", subTitle: "Holiday rentals" },
    { title: "Sherwood Forest", subTitle: "Cabin rentals" },
    { title: "Florence", subTitle: "House rentals" },
    { title: "South Haven", subTitle: "Holiday rentals" },
    { title: "Málaga", subTitle: "Cottage rentals" },
    { title: "Dartmouth", subTitle: "Flat rentals" },
    { title: "Leavenworth", subTitle: "Apartment rentals" },
  ],
  [
    { title: "Lake Martin", subTitle: "Pet-friendly rentals" },
    { title: "North Rim", subTitle: "Holiday rentals" },
    { title: "Emerald Lake", subTitle: "Holiday rentals" },
    { title: "Shaver Lake", subTitle: "Holiday rentals" },
    { title: "The Blue Mountains", subTitle: "Holiday rentals" },
    { title: "Colorado Springs", subTitle: "Holiday rentals" },
    { title: "Vail", subTitle: "Holiday rentals" },
    { title: "Jekyll Island", subTitle: "Rentals with pools" },
    { title: "Banff", subTitle: "House rentals" },
    { title: "Payson", subTitle: "Holiday rentals" },
    { title: "Vancouver Island", subTitle: "Apartment rentals" },
    { title: "South Lake Tahoe", subTitle: "Holiday rentals" },
    { title: "West Kelowna", subTitle: "Beachfront rentals" },
    { title: "Denver", subTitle: "Holiday rentals" },
    { title: "Winter Park", subTitle: "Cabin rentals" },
    { title: "Lake Lanier", subTitle: "Cabin rentals" },
    { title: "Nerja", subTitle: "Villa rentals" },
    { title: "Pinetop-Lakeside", subTitle: "Cabin rentals" },
    { title: "Victoria", subTitle: "Villa rentals" },
    { title: "Cultus Lake", subTitle: "Holiday rentals" },
    { title: "Gran Canaria", subTitle: "Bungalow rentals" },
    { title: "Durango", subTitle: "Cabin rentals" },
    { title: "Salcombe", subTitle: "Holiday rentals" },
    { title: "Corfu", subTitle: "Cottage rentals" },
    { title: "Greer", subTitle: "Holiday rentals" },
    { title: "Red Rock", subTitle: "Cabin rentals" },
    { title: "Idyllwild-Pine Cove", subTitle: "Holiday rentals" },
    { title: "Georgian Bay", subTitle: "Holiday rentals" },
    { title: "Lanzarote", subTitle: "Family-friendly rentals" },
    { title: "Estes Park", subTitle: "Flat rentals" },
    { title: "Swanage", subTitle: "Cabin rentals" },
    { title: "McCall", subTitle: "Pet-friendly rentals" },
    { title: "Lake Havasu City", subTitle: "House rentals" },
    { title: "Dinner Plain", subTitle: "Pet-friendly rentals" },
    { title: "Mammoth Lakes", subTitle: "Holiday rentals" },
    { title: "Manitoulin Island", subTitle: "Cottage rentals" },
    { title: "Castle Hill", subTitle: "Holiday rentals" },
    { title: "Grand Lake", subTitle: "Holiday rentals" },
    { title: "Cape Coral", subTitle: "Holiday rentals" },
    { title: "Clear Lake", subTitle: "Apartment rentals" },
    { title: "Lake Powell", subTitle: "Holiday rentals" },
    { title: "Streaky Bay", subTitle: "Holiday rentals" },
    { title: "Palm Desert", subTitle: "Villa rentals" },
    { title: "Ottawa River", subTitle: "Holiday rentals" },
    { title: "Aspen", subTitle: "Cottage rentals" },
    { title: "Keystone", subTitle: "Cabin rentals" },
    { title: "Blue Ridge", subTitle: "Cabin rentals" },
    { title: "Lough Eske", subTitle: "Holiday rentals" },
    { title: "Lake Cumberland", subTitle: "Cabin rentals" },
    { title: "Torch Lake", subTitle: "Beachfront rentals" },
    { title: "West Yellowstone", subTitle: "Apartment rentals" },
    { title: "Adirondack Mountains", subTitle: "Holiday rentals" },
    { title: "Lake Gaston", subTitle: "Cabin rentals" },
    { title: "Medicine Park", subTitle: "Holiday rentals" },
    { title: "Portland", subTitle: "House rentals" },
    { title: "Isle of Mull", subTitle: "Cottage rentals" },
    { title: "Traverse City", subTitle: "Lakehouse rentals" },
    { title: "Mount Charleston", subTitle: "Holiday rentals" },
    { title: "Lake Placid", subTitle: "House rentals" },
    { title: "Lake Lure", subTitle: "Holiday rentals" },
    { title: "Turner Falls", subTitle: "Holiday rentals" },
    {
      title: "Northern Oregon Coast Range Sunriver",
      subTitle: "Holiday rentals",
    },
    { title: "Holiday rentals", subTitle: "Robe" },
    { title: "South Portland", subTitle: "Holiday rentals" },
    { title: "Upper Peninsula of Michigan", subTitle: "Holiday rentals" },
    { title: "Cloudcroft", subTitle: "House rentals" },
    { title: "Niagara Falls", subTitle: "Cabin rentals" },
    { title: "Lake Norman of Catawba", subTitle: "Holiday rentals" },
    { title: "Muskoka Lakes", subTitle: "Holiday rentals" },
    { title: "Lake Harmony", subTitle: "Holiday rentals" },
    { title: "Mountain Rest", subTitle: "Holiday rentals" },
    { title: "Deep Creek Lake", subTitle: "Chalet rentals" },
    { title: "Branson", subTitle: "Rentals with pools" },
    { title: "Red River", subTitle: "House rentals" },
    { title: "Bald Head Island", subTitle: "Flat rentals" },
    { title: "Mount Airy", subTitle: "Holiday rentals" },
    { title: "Tobermory", subTitle: "Cottage rentals" },
    { title: "Mount Pocono", subTitle: "Holiday rentals" },
    { title: "St Helens", subTitle: "Holiday rentals" },
    { title: "Lake Michigan Beach", subTitle: "Beach house rentals" },
    { title: "Lake of the Ozarks", subTitle: "Holiday rentals" },
    { title: "Bellingen", subTitle: "Holiday rentals" },
    { title: "Bryson City", subTitle: "Apartment rentals" },
    { title: "Oak Island", subTitle: "Beachfront rentals" },
    { title: "Bend", subTitle: "Flat rentals" },
    { title: "Mont-Tremblant", subTitle: "Chalet rentals" },
    { title: "United States", subTitle: "Holiday rentals" },
    { title: "Lakeside", subTitle: "Holiday rentals" },
    { title: "Big Sky", subTitle: "Holiday rentals" },
    { title: "Brunswick Heads", subTitle: "Holiday rentals" },
    { title: "Emerald Isle", subTitle: "Rentals with pools" },
    { title: "Geneva-on-the-Lake", subTitle: "Holiday rentals" },
    { title: "Crater Lake", subTitle: "Cabin rentals" },
    { title: "Aviemore", subTitle: "Flat rentals" },
    { title: "Canyon Lake", subTitle: "Apartment rentals" },
    { title: "Lake Austin", subTitle: "Holiday rentals" },
    { title: "Port Isaac", subTitle: "Holiday rentals" },
    { title: "Mount Buller", subTitle: "Holiday rentals" },
    { title: "Lake Chelan", subTitle: "Holiday rentals" },
    { title: "Lake Geneva", subTitle: "Rentals with pools" },
    { title: "Lake Buchanan", subTitle: "Lakehouse rentals" },
    { title: "Moab", subTitle: "Apartment rentals" },
    { title: "Port Campbell", subTitle: "Cottage rentals" },
    { title: "Lake Crescent", subTitle: "Holiday rentals" },
    { title: "Wisconsin Dells", subTitle: "Holiday rentals" },
    { title: "Betws-y-Coed", subTitle: "Holiday rentals" },
    { title: "Mount Zion", subTitle: "Holiday rentals" },
    { title: "Wilsons Promontory", subTitle: "Holiday rentals" },
    { title: "Lake Quinault", subTitle: "Cottage rentals" },
    { title: "Filey", subTitle: "Cottage rentals" },
    { title: "Moraira", subTitle: "Holiday rentals" },
    { title: "Shenandoah", subTitle: "Cabin rentals" },
    { title: "Quinault", subTitle: "Holiday rentals" },
    { title: "Fort William", subTitle: "House rentals" },
    { title: "Inverloch", subTitle: "Holiday rentals" },
    { title: "Smith Mountain Lake", subTitle: "Holiday rentals" },
    { title: "Skamania", subTitle: "Holiday rentals" },
    { title: "Loch Lomond", subTitle: "Holiday rentals" },
    { title: "Metung", subTitle: "Holiday rentals" },
    { title: "Snowdon", subTitle: "Holiday rentals" },
    { title: "Snowshoe", subTitle: "Holiday rentals" },
    { title: "Geneva-on-the-Lake", subTitle: "Holiday rentals" },
  ],
  [
    { title: "Blue Mountains", subTitle: "House rentals" },
    { title: "Pine Mountain", subTitle: "Holiday rentals" },
    { title: "Snowdon", subTitle: "Holiday rentals" },
    { title: "Blowing Rock", subTitle: "Cottage rentals" },
    { title: "Stone Mountain", subTitle: "Cabin rentals" },
    { title: "Cabins", subTitle: "Holiday rentals" },
    { title: "Sedona", subTitle: "Cabin rentals" },
    { title: "Boone", subTitle: "Holiday rentals" },
    { title: "Hochatown", subTitle: "Holiday rentals" },
    { title: "Smith Mountain Lake", subTitle: "Holiday rentals" },
    { title: "Mount Buller", subTitle: "Holiday rentals" },
    { title: "Mount Zion", subTitle: "Holiday rentals" },
    { title: "Shenandoah", subTitle: "Cabin rentals" },
  ],
  [
    { title: "Dauphin Island", subTitle: "House rentals" },
    { title: "Hamilton Island", subTitle: "Holiday rentals" },
    { title: "Big Sur", subTitle: "Holiday rentals" },
    { title: "Laguna Beach", subTitle: "Flat rentals" },
    { title: "Palm Springs", subTitle: "Family-friendly rentals" },
    { title: "Fuerteventura", subTitle: "Holiday rentals" },
    { title: "Blackpool", subTitle: "House rentals" },
    { title: "Anna Maria Island", subTitle: "Holiday rentals" },
    { title: "Fort Morgan", subTitle: "Holiday rentals" },
    { title: "Lancelin", subTitle: "Holiday rentals" },
    { title: "Bodega Bay", subTitle: "Holiday rentals" },
    { title: "Long Beach", subTitle: "Apartment rentals" },
    { title: "Pismo Beach", subTitle: "Cabin rentals" },
    { title: "Puerto del Carmen", subTitle: "Holiday rentals" },
    { title: "Isle of Wight", subTitle: "Holiday rentals" },
    { title: "Boca Grande", subTitle: "Holiday rentals" },
    { title: "Gulf Shores", subTitle: "Holiday rentals" },
    { title: "Melbourne Beach", subTitle: "Beachfront rentals" },
    { title: "Cambria", subTitle: "Holiday rentals" },
    { title: "Malibu", subTitle: "Bungalow rentals" },
    { title: "Santa Cruz", subTitle: "Cabin rentals" },
    { title: "Tenerife", subTitle: "Villa rentals" },
    { title: "Newquay", subTitle: "Flat rentals" },
    { title: "Bradenton", subTitle: "Holiday rentals" },
    { title: "Bruny Island", subTitle: "Holiday rentals" },
    { title: "Moonta Bay", subTitle: "Beachfront rentals" },
    { title: "Cayucos", subTitle: "Holiday rentals" },
    { title: "Mission Beach", subTitle: "Holiday rentals" },
    { title: "Santa Monica", subTitle: "Holiday rentals" },
    { title: "Ayia Napa", subTitle: "House rentals" },
    { title: "Weymouth", subTitle: "Holiday rentals" },
    { title: "Cape San Blas", subTitle: "Beach house rentals" },
    { title: "Crescent Head", subTitle: "Pet-friendly rentals" },
    { title: "Ocean Grove", subTitle: "Beachfront rentals" },
    { title: "Huntington Beach", subTitle: "House rentals" },
    { title: "Newport Beach", subTitle: "Bungalow rentals" },
    { title: "Sea Ranch", subTitle: "Pet-friendly rentals" },
    { title: "Bethany Beach", subTitle: "Beach house rentals" },
    { title: "Albufeira", subTitle: "Flat rentals" },
    { title: "Captiva", subTitle: "Holiday rentals" },
    { title: "Gerringong", subTitle: "Holiday rentals" },
    { title: "Majorca", subTitle: "House rentals" },
    { title: "la Jolla Shores Beach", subTitle: "Holiday rentals" },
    { title: "Oceanside", subTitle: "Cottage rentals" },
    { title: "Playa Blanca", subTitle: "Holiday rentals" },
    { title: "Dewey Beach", subTitle: "Rentals with pools" },
    { title: "Alys Beach", subTitle: "Pet-friendly rentals" },
    { title: "Clearwater Beach", subTitle: "Apartment rentals" },
    { title: "Cocoa Beach", subTitle: "Beach house rentals" },
    { title: "Fort Walton Beach", subTitle: "Holiday rentals" },
    { title: "Key Largo", subTitle: "Holiday rentals" },
    { title: "Miami Beach", subTitle: "Beach house rentals" },
    { title: "Panama City Beach", subTitle: "Holiday rentals" },
    { title: "Sarasota", subTitle: "House rentals" },
    { title: "Tampa", subTitle: "Beach house rentals" },
    { title: "Kapalua", subTitle: "Flat rentals" },
    { title: "Daytona Beach", subTitle: "Beach apartment rentals" },
    { title: "Grayton Beach", subTitle: "Holiday rentals" },
    { title: "Madeira Beach", subTitle: "Apartment rentals" },
    { title: "Miramar Beach", subTitle: "House rentals" },
    { title: "Pensacola Beach", subTitle: "Beachfront rentals" },
    { title: "Seagrove Beach", subTitle: "House rentals" },
    { title: "West Palm Beach", subTitle: "Holiday rentals" },
    { title: "Kauai", subTitle: "House rentals" },
    { title: "Destin", subTitle: "Beach apartment rentals" },
    { title: "Gulf of Mexico", subTitle: "Holiday rentals" },
    { title: "Marathon", subTitle: "House rentals" },
    { title: "Naples", subTitle: "Holiday rentals" },
    { title: "Perdido Key", subTitle: "Holiday rentals" },
    { title: "Seaside", subTitle: "Beach house rentals" },
    { title: "Bora-Bora", subTitle: "Holiday rentals" },
    { title: "Kihei", subTitle: "Beach house rentals" },
    { title: "Englewood", subTitle: "Cottage rentals" },
    { title: "Indian Rocks Beach", subTitle: "Bungalow rentals" },
    { title: "Marco Island", subTitle: "Cottage rentals" },
    { title: "Navarre Beach", subTitle: "Holiday rentals" },
    { title: "Rosemary Beach", subTitle: "Holiday rentals" },
    { title: "South Beach", subTitle: "Beach apartment rentals" },
    { title: "Tybee Island", subTitle: "Flat rentals" },
    { title: "Ko Olina Beach", subTitle: "Holiday rentals" },
    { title: "Fort Lauderdale", subTitle: "Villa rentals" },
    { title: "Islamorada", subTitle: "Bungalow rentals" },
    { title: "Mexico Beach", subTitle: "Beach house rentals" },
    { title: "New Smyrna Beach", subTitle: "Pet-friendly rentals" },
    { title: "Saint George Island", subTitle: "Apartment rentals" },
    { title: "St. Augustine Beach", subTitle: "Apartment rentals" },
    { title: "Honolulu", subTitle: "Beach house rentals" },
    { title: "Maui", subTitle: "House rentals" },
    { title: "Fort Myers Beach", subTitle: "Beach apartment rentals" },
    { title: "Jacksonville Beach", subTitle: "Beachfront rentals" },
    { title: "Miami Beach", subTitle: "Holiday rentals" },
    { title: "Okaloosa Island", subTitle: "Flat rentals" },
    { title: "Santa Rosa Beach", subTitle: "Apartment rentals" },
    { title: "St. Pete Beach", subTitle: "Cottage rentals" },
    { title: "Kailua-Kona", subTitle: "Beachfront rentals" },
    { title: "Old Orchard Beach", subTitle: "Pet-friendly rentals" },
    { title: "Jersey Shore", subTitle: "Cottage rentals" },
    { title: "Fire Island", subTitle: "Holiday rentals" },
    { title: "Holden Beach", subTitle: "Cottage rentals" },
    { title: "Surf City", subTitle: "Holiday rentals" },
    { title: "Seaside", subTitle: "Holiday rentals" },
    { title: "Charleston Oceanfront Villas", subTitle: "Holiday rentals" },
    { title: "Myrtle Beach", subTitle: "Beach apartment rentals" },
    { title: "Costa Adeje", subTitle: "Beachfront rentals" },
    { title: "Wells", subTitle: "Holiday rentals" },
    { title: "North Wildwood", subTitle: "Holiday rentals" },
    { title: "Montauk", subTitle: "Pet-friendly rentals" },
    { title: "Kitty Hawk", subTitle: "Holiday rentals" },
    { title: "Wilmington", subTitle: "Beachfront rentals" },
    { title: "Carvoeiro", subTitle: "Holiday rentals" },
    { title: "Edisto Beach", subTitle: "Beach house rentals" },
    { title: "Pawleys Island", subTitle: "Pet-friendly rentals" },
    { title: "Costa del Sol Occidental", subTitle: "Holiday rentals" },
    { title: "Cape Cod", subTitle: "Flat rentals" },
    { title: "Ocean City", subTitle: "Holiday rentals" },
    { title: "Ocean Beach", subTitle: "Beach house rentals" },
    { title: "Kure Beach", subTitle: "Beach house rentals" },
    { title: "Wrightsville Beach", subTitle: "Beach apartment rentals" },
    { title: "Gold Coast", subTitle: "Family-friendly rentals" },
    { title: "Folly Beach", subTitle: "Pet-friendly rentals" },
    { title: "Seabrook Island", subTitle: "Holiday rentals" },
    { title: "Fuengirola", subTitle: "Holiday rentals" },
    { title: "Nantucket", subTitle: "Holiday rentals" },
    { title: "Sea Isle City", subTitle: "Holiday rentals" },
    { title: "Atlantic Beach", subTitle: "House rentals" },
    { title: "Nags Head", subTitle: "Holiday rentals" },
    { title: "Sauble Beach", subTitle: "Cottage rentals" },
    { title: "Moreton Island", subTitle: "Holiday rentals" },
    { title: "Fripp Island", subTitle: "Holiday rentals" },
    { title: "Sullivan's Island", subTitle: "Pet-friendly rentals" },
    { title: "Los Cristianos", subTitle: "Beach house rentals" },
    { title: "Biloxi", subTitle: "House rentals" },
    { title: "Stone Harbor", subTitle: "Holiday rentals" },
    { title: "Carolina Beach", subTitle: "Holiday rentals" },
    { title: "Ocean Isle Beach", subTitle: "Beach house rentals" },
    { title: "Wasaga Beach", subTitle: "Holiday rentals" },
    { title: "Block Island", subTitle: "Holiday rentals" },
    { title: "Isle of Palms", subTitle: "House rentals" },
    { title: "Surfside Beach", subTitle: "Beach house rentals" },
    { title: "Corpus Christi", subTitle: "Flat rentals" },
    { title: "Avalon", subTitle: "Holiday rentals" },
    { title: "Hyams Beach", subTitle: "Beach house rentals" },
    { title: "Alicante", subTitle: "Holiday rentals" },
    { title: "South Padre Island", subTitle: "Pet-friendly rentals" },
    { title: "Seabrook", subTitle: "Holiday rentals" },
    { title: "Surfside Beach", subTitle: "Beach house rentals" },
    { title: "Jurien Bay", subTitle: "Holiday rentals" },
    { title: "Bournemouth", subTitle: "Cottage rentals" },
    { title: "New Quay", subTitle: "Holiday rentals" },
    { title: "Anglesea", subTitle: "Holiday rentals" },
    { title: "Abersoch", subTitle: "Pet-friendly rentals" },
  ],
  [
    { title: "Yurt Rentals", subTitle: "United States" },
    { title: "Farm Houses", subTitle: "United States" },
    { title: "Cottage Rentals", subTitle: "United States" },
    { title: "Condo Rentals", subTitle: "United States" },
    { title: "Big Cottages", subTitle: "Australia" },
    { title: "Yurt Rentals", subTitle: "United Kingdom" },
    { title: "Coastal Cottages", subTitle: "United Kingdom" },
    { title: "Farm Cottages", subTitle: "United Kingdom" },
    { title: "Holiday Cottages", subTitle: "United Kingdom" },
    { title: "Holiday Apartments", subTitle: "Australia" },
    { title: "Large Villas", subTitle: "United Kingdom" },
    { title: "Holiday Cottages with a Hot Tub", subTitle: "United Kingdom" },
    { title: "Beach Cabins", subTitle: "United Kingdom" },
    { title: "Castle Rentals", subTitle: "United States" },
    { title: "Cabin Rentals", subTitle: "Australia" },
    { title: "Mansion Rentals", subTitle: "United States" },
    { title: "Holiday Houses", subTitle: "United States" },
    { title: "House Rentals with a Pool", subTitle: "United States" },
    { title: "Beach Condos", subTitle: "United States" },
    { title: "Pet-Friendly Vacation Rentals", subTitle: "United States" },
    { title: "Pet-Friendly Beach Rentals", subTitle: "United States" },
    { title: "Houseboats", subTitle: "United States" },
    { title: "Luxury Cabins", subTitle: "United Kingdom" },
    { title: "Villa Rentals", subTitle: "United Kingdom" },
    { title: "Cabin Rentals with a Pool", subTitle: "United States" },
    { title: "Beachfront Rentals", subTitle: "United States" },
    { title: "Pet-Friendly Cabin Rentals", subTitle: "United States" },
    { title: "Holiday Caravans", subTitle: "United Kingdom" },
    { title: "Dog-Friendly Cottages", subTitle: "United Kingdom" },
    { title: "Private Island Rentals", subTitle: "United States" },
    { title: "Holiday Chalets", subTitle: "United Kingdom" },
    { title: "Bungalow Rentals", subTitle: "United States" },
    { title: "Big House Rentals", subTitle: "United States" },
    { title: "Apartments with a Hot Tub", subTitle: "United States" },
    { title: "Beach Villas", subTitle: "United Kingdom" },
    { title: "Luxury Dog-Friendly Cottages", subTitle: "United Kingdom" },
    { title: "Holiday Bungalows", subTitle: "United Kingdom" },
    { title: "Private Holiday Rentals", subTitle: "United Kingdom" },
    { title: "Villas with a Pool", subTitle: "United Kingdom" },
    { title: "Beach Houses", subTitle: "United Kingdom" },
  ],
  [
    { title: "Amazing Pools", subTitle: "" },
    { title: "Countryside", subTitle: "" },
    { title: "OMG!", subTitle: "" },
    { title: "Arctic", subTitle: "" },
    { title: "Design", subTitle: "" },
    { title: "Tiny Homes", subTitle: "" },
    { title: "Camping", subTitle: "" },
    { title: "Earth Homes", subTitle: "" },
    { title: "Towers", subTitle: "" },
    { title: "Camper Vans", subTitle: "" },
    { title: "Farms", subTitle: "" },
    { title: "Windmills", subTitle: "" },
    { title: "Castles", subTitle: "" },
    { title: "National Parks", subTitle: "" },
    { title: "Luxe", subTitle: "" },
    { title: "Containers", subTitle: "" },
    { title: "Vineyards", subTitle: "" },
  ],
  [
    { title: "London", subTitle: "England" },
    { title: "Amsterdam", subTitle: "North Holland" },
    { title: "Tokyo", subTitle: "" },
    { title: "Santorini", subTitle: "Greece" },
    { title: "Boston", subTitle: "Massachusetts" },
    { title: "Austin", subTitle: "Texas" },
    { title: "Nashville", subTitle: "Tennessee" },
    { title: "France", subTitle: "Paris, Île-de-France" },
    { title: "Miami", subTitle: "Florida" },
    { title: "Vienna", subTitle: "" },
    { title: "Mexico City", subTitle: "" },
    { title: "San Diego", subTitle: "California" },
    { title: "Maui", subTitle: "Hawaii" },
    { title: "Charleston", subTitle: "South Carolina" },
    { title: "Berlin", subTitle: "" },
    { title: "New York", subTitle: "New York" },
    { title: "Madrid", subTitle: "Community of Madrid" },
    { title: "Athens", subTitle: "Greece" },
    { title: "Venice", subTitle: "Veneto" },
    { title: "Chicago", subTitle: "Illinois" },
    { title: "New Orleans", subTitle: "Louisiana" },
    { title: "Los Cabos", subTitle: "Baja California Sur" },
    { title: "Canada", subTitle: "" },
    { title: "Barcelona", subTitle: "Catalonia" },
    { title: "Los Angeles", subTitle: "California" },
    { title: "Prague", subTitle: "Czechia" },
    { title: "Playa del Carmen", subTitle: "Quintana Roo" },
    { title: "Seattle", subTitle: "Washington" },
    { title: "San Juan", subTitle: "San Juan" },
    { title: "Savannah", subTitle: "Georgia" },
    { title: "Toronto", subTitle: "Ontario" },
    { title: "İstanbul", subTitle: "" },
    { title: "Rome", subTitle: "Lazio" },
    { title: "Orlando", subTitle: "Florida" },
    { title: "San Francisco", subTitle: "California" },
    { title: "Washington", subTitle: "District of Columbia" },
    { title: "Oʻahu", subTitle: "Hawaii" },
    { title: "Dubai", subTitle: "" },
    { title: "Switzerland", subTitle: "" },
    { title: "Bali", subTitle: "Indonesia" },
    { title: "Lisbon", subTitle: "Lisbon" },
    { title: "Cancún", subTitle: "Quintana Roo" },
    { title: "Las Vegas", subTitle: "Nevada" },
    { title: "Atlanta", subTitle: "Georgia" },
    { title: "Denver", subTitle: "Colorado" },
    { title: "Seoul", subTitle: "" },
    { title: "Budapest", subTitle: "Hungary" },
  ],
];

export default Lists;